{% set version = "3.2.0" %}

package:
  name: lektor
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/L/Lektor/Lektor-{{ version }}.tar.gz
  sha256: 5ab0c55aaea3cb98efdbf33b44adfd8291d0724e8849892eb13767d5cdb1fe40

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - lektor = lektor.cli:main

requirements:
  build:
    - pip
    - python
  run:
    - babel
    - click >=6.0
    - exifread
    - filetype >=1.0.7
    - flask
    - inifile
    - jinja2 >=2.11
    - mistune >=0.7.0,<2
    - ndg-httpsclient
    - nodejs
    - pip
    - pyasn1
    - pyopenssl >=0.13
    - python
    - python-slugify
    - requests
    - setuptools
    - watchdog
    - werkzeug <1

test:
  imports:
    - lektor

  commands:
    - lektor --help

about:
  home: https://getlektor.com
  license: BSD-3-Clause
  license_file: LICENSE
  license_family: BSD
  summary: The lektor static file content management system.
  description: |
    A flexible and powerful static content management system for building
    complex and beautiful websites out of flat files for people who do not
    want to make a compromise between a CMS and a static blog engine.
  dev_url: https://github.com/lektor/lektor
  doc_url: https://www.getlektor.com/docs

extra:
  recipe-maintainers:
    - goanpeca
    - nixjdm
