{% set version = "3.1.3" %}

package:
  name: lektor
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/L/Lektor/Lektor-{{ version }}.tar.gz
  sha256: 60a83e7a100780a58553324b396b0df32a2f584452184efbf87acefed85e564d

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  entry_points:
    - lektor = lektor.cli:main

requirements:
  build:
    - python
    - pip
  run:
    - babel
    - click >=6.0
    - exifread
    - flask
    - inifile
    - jinja2 >=2.4
    - mistune >=0.7.0
    - ndg-httpsclient
    - nodejs
    - pyasn1
    - pyopenssl >=0.13
    - python
    - requests
    - watchdog

test:
  imports:
    - lektor

  commands:
    - lektor --help

about:
  home: https://getlektor.com
  license: BSD 3-Clause
  license_family: BSD
  summary: The lektor static file content management system.
  description: |
    A flexible and powerful static content management system for building
    complex and beautiful websites out of flat files for people who do not
    want to make a compromise between a CMS and a static blog engine.
  dev_url: https://github.com/lektor/lektor
  doc_url: https://www.getlektor.com/docs

extra:
  recipe-maintainers:
    - goanpeca
    - rlaverde
