{% set version = "3.3.4" %}

package:
  name: lektor
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/L/Lektor/Lektor-{{ version }}.tar.gz
  sha256: 02a2840cab815579a3fa2df2d07360d8d3a21c71586d01a192bd35c7c76d0979

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - lektor = lektor.cli:main

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools >=45
    - setuptools_scm >=6
  run:
    - babel
    - click >=6.0
    - exifread
    - filetype >=1.0.7
    - flask
    - inifile >=0.4.1
    - jinja2 >=3.0
    - markupsafe
    - mistune >=0.7.0, <2
    - nodejs
    - pip
    - python >=3.6
    - python-slugify
    - pytz
    - requests
    - setuptools
    - watchdog
    - werkzeug <3

test:
  imports:
    - lektor

  commands:
    - pip check
    - lektor --help
    - lektor --version

about:
  home: https://getlektor.com
  license: BSD-3-Clause
  license_file: LICENSE
  license_family: BSD
  summary: The lektor static file content management system.
  description: |
    A flexible and powerful static content management system for building
    complex and beautiful websites out of flat files for people who do not
    want to make a compromise between a CMS and a static blog engine.
  dev_url: https://github.com/lektor/lektor
  doc_url: https://www.getlektor.com/docs

extra:
  recipe-maintainers:
    - CAM-Gerlach
    - goanpeca
    - nixjdm
