travis:
  secure:
    BINSTAR_TOKEN: MhTelKgXOQq3wLLDcIZVCPqILUV/ei8RuHiQUxpNpZsV0lFpGUcOyU3v+FheHzC+ZkEa4XLcr64J6lI7l+gCJU0O/QiQHf1OZ8UWXjIUFzVo7ZrypcfJpxElS3JjNsXGgSn6/WzYPqumTfeCHNqd0t4H9/dUO6E+hcap8pEyuvS5VbGhGeyCgHHhDP2kTwDvT9vtNwQUhsH19bFg1T0rUuXHMpTYXE8X3oVq6cNLW/vq8cHI+y+BicCTuo02XPa1onPuYfkOnr6Ze8BBF+ZrhnXdlPVEnHJv8UxaJaCQADGZX6eCKGiHjZOBDmNJADVZzJAlla5pK+nd0qyQXRN4b3ASltRvI7URaTfWvgzKyQKelqJeQ0eGQDt2mbnB6zj6Affjq63RM+mWCjDUsCvJ9MMbWDar12fqnrXKq+4lnKEuh5c4a2ZCC0g9w9GnoIKskbu1xmOYNRfqSMQMHhkVP1gWK4d2arD5Hc+KEksoc62mUfvMPYPAWiiv1fRaYauAKK7vEMP62DJZm+WwZSfuVd9KXaBWmRJvmaaHfYELhTRFyvneisQbR3gNJF1m8OM9iS6/ORGtqDtTZx3gAiRxUHDwRp/S1gNEGPQQTE2ImBermNjYUZJ072+LHTnOuJ6fqfxe97TMJ078tG3qm7MbBO5MSeu5spFXvVmYZjRDriU=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
