travis:
  secure:
    BINSTAR_TOKEN: WAFaQnd32GyGD6xbC2k3shg1VDBA2HsIL7P/2KWR4aKkwOED1FyBy2k56iauOxDpHFvOxBRf/sSJFv+tHoOniBF2uSsF1Bz5lIMl9yLHw1HeHWw9qobFEvu0uUI+9zxxWPaPfQ4VKhGv3T9PGi54LcGNSDZ1lEju64ep5tT5PdXFnXLDwxTLQ2fiRq1uCb4i5So9S4bfiY3k/Aw1PcAT+llnh76qeW5YZuCggMI+J8tP8Z/Ukim1WqLEhti9hzd936P21wzBKpObmHR32NSAYzkR/5bF/DEC6hL9tAFes0lq8EZmL+VWzbg5tlQ0iWv0ywv4UFikDDFSmiKPv9bzucjENXFziY2M2cDnCyFs896B2j87obJoJH4tlucmaJxs5P6jrF4U8sz/by/lHfuAfALDQ70OUl4sNxWfUlDYNW2RvZc/U1DbsXHEVmJezYlP2qLygKRijidHVPsd1zWsXi1yUXrU0QukqvyKnhv5SZ6jAt/VPWE4j4Gad/uh9wG5kyG+tL9KP1CieqmhGm9ADcdM5rGbjIZSSbEa+QaFnR/E4RnMYjeNWnwUybXxxNGAo/bKEVbetCX0iCUpnetydc0eu/tQqeFQ7GggHSU4HRjLcK2jpc7v1lLc9/1uvwlZRnacaw8CEihtQDvXfYSVYAeS+TDAhup+DDbiEd/QnQw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
