travis:
  secure:
    BINSTAR_TOKEN: N9OTtL4A0K3zLlm4aVm6p+l0NQCtBv8m/SXDQCORWrmKdMur8iOe3BO/D3f3csAGb2h3lA4K69/RkSqQugkSuIrG+/Hl//IhDAh8tCObzmfg7mQLCzq4KzsippjwQSkJCZQguiYMWUHb453Ss2BbMvv36xopu7zQEthbk73ow5qxNjqpMNrZRapV76UiqmXUB8Ti8CP/0N3GHaFdVz4+aD7yCgKOc7Oq5KpuxDVbZF6YD0mk/wrwZqB+olyyJ8ze/pt7groogcl21UY7Ol4Ub+Gd1fNplAFOHEdaoDsLSWBjjZZRqVmnrphXj1kG2tSlLRRuesvtdPVcZacVLvhQgRbs1AXxYxzdM2QNCarimYdU0sWDc94LLRCBSysIH02xVgoFozVEQNmgL1YVdGXq4SA8XsWWvVd0H35A6BAsLYWt6K7s4fpYvtMt2KvktGi5WvirmZXmR8cJnHeZswzh3CUqtAdThHQ2/raAuPLcxd3/dHBqzFTaxJxecsfAcvB6JyKR/S0ylYIbqn2Z/JHnXvlxtRiO1V7vmOmysIFV0XYpe6tOwqP2qy7XUih9vBfeJsbiUywUToHL+iy796TSwpwwa6Soc09P5o20Zcx2PLUkOjMIxgm1cG6zDWB6cclEfnzj/CzmggVYIp009RgTGp7qMnISRPqCVD1+ZfuEVEk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
